name: Self-hosted Action Demo
on:
  workflow_dispatch:

jobs:
  Self-hosted-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: ls -l
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt run
  Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: ls -l
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt run
